services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - app-network
    cpus: 2
    mem_limit: 1g
    mem_reservation: 512m
    memswap_limit: 1g
    restart: unless-stopped
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./backend/internal

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - API_URL=${API_URL:-http://localhost:1323/api/v1}
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    cpus: 1
    mem_limit: 512m
    mem_reservation: 256m
    restart: unless-stopped
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./client


networks:
  app-network:
    driver: bridge
