services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "1323:1323"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: ./backend/internal

networks:
  app-network:
    driver: bridge
