services:
  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - app-network
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./backend/internal

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - API_URL=http://server:1323/api/v1
    ports:
      - "3000:3000"
    depends_on:
      - server
    networks:
      - app-network
    # develop:
    #   watch:
    #     - action: rebuild
    #       path: ./client


networks:
  app-network:
    driver: bridge
